# Generated by Django 3.2.6 on 2022-02-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wxapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('passwordHashWithSalt', models.CharField(max_length=1000)),
                ('salt', models.CharField(max_length=200)),
                ('nickname', models.CharField(default='', max_length=200)),
                ('auth', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=200, unique=True)),
                ('problem', models.CharField(max_length=200)),
                ('problemType', models.CharField(max_length=20)),
                ('inspection', models.CharField(max_length=200)),
                ('processAndWays', models.CharField(max_length=200)),
                ('finalEffect', models.CharField(max_length=100)),
                ('companions', models.CharField(max_length=30)),
                ('appointment_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapi.appointment', to_field='uuid')),
                ('manage_username', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='manageAPI.user', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='DealAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('appointment_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapi.appointment', to_field='uuid')),
                ('manage_username', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='manageAPI.user', to_field='username')),
            ],
        ),
    ]
