# Generated by Django 3.1.13 on 2021-11-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('passwordHashWithSalt', models.CharField(max_length=1000)),
                ('salt', models.CharField(max_length=200)),
                ('nickname', models.CharField(default='', max_length=200)),
                ('auth', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
