# Generated by Django 3.2.6 on 2022-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAPI', '0002_alter_summaryappointment_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryappointment',
            name='pcbrand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='summaryappointment',
            name='pcmodel',
            field=models.CharField(default='', max_length=30),
        ),
    ]
