# Generated by Django 3.2.6 on 2022-03-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAPI', '0003_auto_20220208_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryappointment',
            name='imgurl',
            field=models.CharField(max_length=500),
        ),
    ]
