# Generated by Django 3.2.6 on 2022-01-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='test',
        ),
    ]
