# Generated by Django 3.2 on 2021-09-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0002_alter_mainproblemtype_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='sourseInfo',
            new_name='sourcesInfo',
        ),
    ]
