# Generated by Django 3.2.7 on 2021-10-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0003_rename_sourseinfo_appointment_sourcesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='submitTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
