# Generated by Django 3.2.7 on 2021-10-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0005_alter_appointment_submittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='applyTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='submitTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
